# Backend requerido para que funcionen las esquinas redondeadas
backend = "glx";

# Esquinas redondeadas (mínimas)
corner-radius = 5;

# Transparencia / Opacidad
active-opacity = 0.95;
inactive-opacity = 0.85;
